name: Tests plans

on:
  pull_request:
    branches: [acc]
    types: [opened, edited, synchronize]

jobs:
  tests-plan:
    uses: guidion-digital/terrappy/.github/workflows/tfc-test-helper-module-plan.yaml@v1
    permissions:
      contents: read
      pull-requests: read

  release-dry-run:
    needs: tests-plan
    uses: guidion-digital/release-workflows/.github/workflows/github-release-tag-dry-run.yaml@v1
    with:
      branch: ${{ github.ref_name }}
